--JUANA
--Admin12345
--XEPDB1

SELECT USER FROM DUAL;


--Ver todos los usuarios conectados
SELECT username, osuser, machine FROM v$session WHERE username IS NOT NULL;


----Crear tablespace JUANA
CREATE TABLESPACE JUANA
DATAFILE '/opt/oracle/oradata/XE/XEPDB1/JUANA.dbf' SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;


--Consultar que el tablespace JUANA existe
SELECT TABLESPACE_NAME
FROM DBA_TABLESPACES
WHERE TABLESPACE_NAME = 'JUANA';


--Validar la ubicación del tablespace JUANA
SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_DATA_FILES WHERE TABLESPACE_NAME = 'JUANA';


--Crear usuario JUANA en el tablespace JUANA
CREATE USER JUANA IDENTIFIED BY Admin12345
DEFAULT TABLESPACE JUANA
TEMPORARY TABLESPACE temp;


--Desbloquear y Asignar Permisos al usuario JUANA
ALTER USER JUANA ACCOUNT UNLOCK;
GRANT CONNECT, RESOURCE TO JUANA;
ALTER USER JUANA QUOTA UNLIMITED ON USERS;
ALTER USER JUANA QUOTA UNLIMITED ON JUANA;


--Verificar que el usuario JUANA existe en el tablespace JUANA
SELECT USERNAME, DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE
FROM DBA_USERS
WHERE USERNAME = 'JUANA';


--conexion usuario JUANA
--CREAR TABLA
-- Creación de la tabla de productos para Oracle
CREATE TABLE productos (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    precio NUMBER(10, 2) NOT NULL,
    descripcion VARCHAR2(200)
);

-- Inserción de 5 registros de ejemplo
INSERT INTO productos (nombre, precio, descripcion) VALUES ('Laptop Pro', 1200.50, 'Potente laptop para profesionales');
INSERT INTO productos (nombre, precio, descripcion) VALUES ('Teclado Mecánico RGB', 150.75, 'Teclado con switches Cherry MX Red');
INSERT INTO productos (nombre, precio, descripcion) VALUES ('Monitor Curvo 27"', 450.00, 'Monitor ultrawide para una experiencia inmersiva');
INSERT INTO productos (nombre, precio, descripcion) VALUES ('Mouse Inalámbrico Ergonómico', 89.99, 'Diseño cómodo para largas horas de uso');
INSERT INTO productos (nombre, precio, descripcion) VALUES ('Webcam HD 1080p', 65.20, 'Cámara web con micrófono incorporado');

COMMIT;

SELECT * FROM productos;

DROP TABLE productos;


--Eliminar usuario JUANA
DROP USER JUANA;


--Eliminar tablespace JUANA
DROP TABLESPACE JUANA INCLUDING CONTENTS AND DATAFILES;